version: "3.5"

services:
  app:
    build: ./docker/php
    environment:
      AUTORELOAD_PROGRAMS: ""
      AUTORELOAD_ANY_FILES: 0
    ports:
      - "8080:9501"
    volumes:
      - ./project:/var/www
