parameters:
  app.env: '%env(string:APP_ENV)%'
  app.debug: '%env(bool:APP_DEBUG)%'
  app.name: '%env(string:APP_NAME)%'

  app.allowed_recursion_level: '%env(int:APP_ALLOWED_RECURSION_LEVEL)%'

  db.driver: pgsql
  db.host: '%env(DB_HOST)%'
  db.port: '%env(int:DB_PORT)%'
  db.name: '%env(DB_NAME)%'
  db.user: '%env(DB_USER)%'
  db.pass: '%env(DB_PASS)%'

  logger.stream: '%env(string:LOGGER_STREAM)%'
  logger.level: '%env(int:LOGGER_LEVEL)%'

  swoole.host: '%env(string:SWOOLE_SERVER_HOST)%'
  swoole.port: '%env(int:SWOOLE_SERVER_PORT)%'
  swoole.options:
    worker_num: '%env(int:SWOOLE_WORKER_NUM)%'
    task_worker_num: '%env(int:SWOOLE_TASK_WORKER_NUM)%'
    task_enable_coroutine: '%env(bool:SWOOLE_TASK_ENABLED_COROUTINE)%'
    dispatch_mode: '%env(int:SWOOLE_DISPATCH_MODE)%'
    daemonize: '%env(int:SWOOLE_DAEMONIZE)%'
    output_buffer_size: '%env(int:SWOOLE_OUTPUT_BUFFER_SIZE)%'
    package_max_length: '%env(int:SWOOLE_PACKAGE_MAX_LENGTH)%'
    http_parse_post: '%env(bool:SWOOLE_HTTP_PARSE_POST)%'
    http_compression: '%env(bool:SWOOLE_HTTP_COMPRESSION)%'
    http_compression_level: '%env(int:SWOOLE_HTTP_COMPRESSION_LEVEL)%'


services:
  _defaults:
    autowire: true
    # we do not have default Symfony interfaces to autoconfigure them
    autoconfigure: false
    bind:
      $appName: '%app.name%'
      $appEnv: '%app.env%'
      $allowedRecursionLevel: '%app.allowed_recursion_level%'

  _instanceof:
    App\Infrastructure\PgSql\ConnectionAwareInterface:
      tags: [ db.connection_aware ]

  App\:
    resource: '../src/*'

  App\Presentation\Http\Controllers\:
    resource: '../src/Presentation/Http/Controllers/'
    public: true

  # This service is retrieved from container directly and must be public
  App\Application:
    public: true

  App\Domain\Sheet\ExpressionEvaluatorInterface: '@App\Infrastructure\Adapter\Expression\Evaluator'
#  App\Domain\Sheet\SheetsStorageInterface: '@App\Infrastructure\Adapter\Storage\ArraySheetsStorage'
  App\Domain\Sheet\SheetsStorageInterface: '@App\Infrastructure\Adapter\Storage\PgSqlSheetsStorage'

  App\DependencyInjection\Factories\RouterFactory:
    arguments:
      $container: '@service_container'
      $projectRootPath: '%app.project_dir%'
      $isDebugEnabled: '%app.debug%'

  App\Infrastructure\Adapter\Storage\ArraySheetsStorage: ~
  App\Infrastructure\Adapter\Storage\PgSqlSheetsStorage: ~

  App\Infrastructure\PgSql\PdoConnectionPool:
    factory: [ '@App\DependencyInjection\Factories\PdoConnectionPoolFactory', 'create' ]
    arguments:
      $driver: '%db.driver%'
      $host: '%db.host%'
      $port: '%db.port%'
      $name: '%db.name%'
      $user: '%db.user%'
      $pass: '%db.pass%'

  App\Infrastructure\PgSql\ConnectionManager:
    arguments:
      $services: !tagged_iterator db.connection_aware

  # 3rd-party services
  ChrisKonnertz\StringCalc\StringCalc: ~

  FastRoute\Dispatcher:
    factory: [ '@App\DependencyInjection\Factories\RouterFactory', 'create' ]

  Psr\Log\LoggerInterface:
    factory: [ '@App\DependencyInjection\Factories\LoggerFactory', 'create' ]
    arguments:
      - '%app.name%'
      - '%logger.stream%'
      - '%logger.level%'

  OpenSwoole\Core\Psr\Middleware\StackHandler:
    arguments:
      - '@App\Presentation\Http\Middlewares\DbContextMiddleware'
      - '@App\Presentation\Http\Middlewares\ErrorHandlerMiddleware'
      - '@App\Presentation\Http\Middlewares\ParseJsonMiddleware'
      - '@App\Presentation\Http\Middlewares\TransactionMiddleware'
      - '@App\Presentation\Http\Middlewares\RoutingMiddleware'

  OpenSwoole\Http\Server:
    arguments:
      - '%swoole.host%'
      - '%swoole.port%'
    calls:
      - set: [ '%swoole.options%' ]
